### ISSUE TITLE
Issue when the user change the payment method for an order to Stripe

### ISSUE THREAD

**Issue by YellowFish085** [FLUX-SE/SyliusPayumStripePlugin#2] opened 2020-05-04 12:01 UTC
- Sylius: v1.7.3
- SyliusPayumStripeCheckoutSessionPlugin: v1.1 (fresh install)

Hello, me again.

There is an issue that makes the Stripe payment fail when the user changes the payment method for an order to Stripe after initially choosing another payment method.

Here is the actual context and steps that made me stumble upon the issue:

- On my project I have 2 payment methods, an offline method and Stripe. If the user choose the offline payment method, a record in the `sylius_payments` table will be created with the following data in the `details` column:

  ```JSON
  {
    "paid": false,
    "status": "pending"
  }
  ```

- Based on my observations, Sylius does not seems to create a new payment record in the `sylius_payments` table when the user change the payment method but instead just update the last payment record if it's still in a new state.

- Because of that, if the user changes the payment method to Stripe the `details` column is not filled with the [correct content](https://github.com/Prometee/SyliusPayumStripeCheckoutSessionPlugin/blob/v1.1.0/src/Provider/DetailsProvider.php#L33) and will instead keep the content set by the previous payment method + other content added by [this method](https://github.com/Prometee/PayumStripe/blob/v1.1.1/src/Action/CaptureAction.php#L32).

- Ultimately, the payment flow fails with the following error:

![Screenshot 2020-05-04 at 12 12 09](https://user-images.githubusercontent.com/11556009/80961686-bde66980-8e0b-11ea-9fba-7a59f7d6c0cb.png)

I'm not familiar with everything related to Sylius and Payum, and how everything works is still blurry for me, but I might have found where the issue could come from. I'll try to be as accurate as possible about what I found, I hope it will be clear enough for you to identify the issue.

When the user changes the payment method, at some point during the whole payment flow Sylius calls the [Sylius\Bundle\PayumBundle\Action\CapturePaymentAction->execute](https://github.com/Sylius/Sylius/blob/v1.7.3/src/Sylius/Bundle/PayumBundle/Action/CapturePaymentAction.php#L42) method. This method will [get the current payment status](https://github.com/Sylius/Sylius/blob/v1.7.3/src/Sylius/Bundle/PayumBundle/Action/CapturePaymentAction.php#L52), which, for Stripe payments, is decided using the [Prometee\PayumStripe\Action\StatusAction->execute](https://github.com/Prometee/PayumStripe/blob/v1.1.1/src/Action/StatusAction.php#L25) method. If the payment status is `'new'`, [this code](https://github.com/Sylius/Sylius/blob/v1.7.3/src/Sylius/Bundle/PayumBundle/Action/CapturePaymentAction.php#L55-L56) will be executed and at some point the [Prometee\SyliusPayumStripeCheckoutSessionPlugin\Action\ConvertPaymentAction->execute](https://github.com/Prometee/SyliusPayumStripeCheckoutSessionPlugin/blob/v1.1.0/src/Action/ConvertPaymentAction.php#L29) method will be called to generate the required data.

But, in the situation where the user changes the payment method from an offline method to Stripe, when the [Sylius\\...\CapturePaymentAction->execute](https://github.com/Sylius/Sylius/blob/v1.7.3/src/Sylius/Bundle/PayumBundle/Action/CapturePaymentAction.php#L42) method starts, a payment record already exists in the DB with a `details` column containing a `status` field that was set to `pending` by the previous payment method. The [Prometee\\...\StatusAction->execute](https://github.com/Prometee/PayumStripe/blob/v1.1.1/src/Action/StatusAction.php#L25) method does not handle this case, and will set the payment status to `unknown`. This will prevent [these lines](https://github.com/Sylius/Sylius/blob/v1.7.3/src/Sylius/Bundle/PayumBundle/Action/CapturePaymentAction.php#L55-L56) from being executed, which will in consequence also prevent the [Prometee\\...\ConvertPaymentAction->execute](https://github.com/Prometee/SyliusPayumStripeCheckoutSessionPlugin/blob/v1.1.0/src/Action/ConvertPaymentAction.php#L29) method from being executed.

I hope the explanation is clear enough, once again I'm sorry that I can't give you a more brief and concise explanation.

**Comment by Prometee** [comment] 2020-05-18 11:18
Sorry for this late answer @YellowFish085, base on what you are explaining I should be able to test this behaviour. But I think there is something missing in the other payment gateway like something canceling the payment after getting back to the page showing the selection of payment methods. I will investigate on this, thanks for the pointing it and explain it 😉

**Comment by Prometee** [comment] 2020-05-18 16:27
@YellowFish085 I'm able to reproduce the bug you described and you are right, because the status is set to unknown the payment fail because the `Convert` is not done. While switching to another gateway the `Payment` entity is updated and not created with a new one unfortunately. I'm currently investigating how Sylius or Payum is handling this. I'll get back to you soon !

**Comment by YellowFish085** [comment] 2020-05-20 11:28
Nice, thank you! (and thank you for the shipping cost issue too :) )

**Comment by oneshoot41** [comment] 2020-07-30 09:41
Hi, first i'd like to thank @Prometee for creating this gateway for those like me who are kind of newbies in the world of Sylius, but is there any chances that this issue was solved or nothing yet ? ^^'

**Comment by Prometee** [comment] 2020-07-30 10:34
@oneshoot41 thanks you 😉

Nothing yet unfortunately. The problem come from the way Sylius is handling the switch between gateways keeping the old payment details value. A way of fixing it is to listen to doctrine event and reset the details data when the payment_gateway_id is changed.

**Comment by oneshoot41** [comment] 2020-07-30 14:03
@Prometee Mmh indeed that could be the temporary solution, but i was thinking if i really needed offline payment on a online shop.. I think i'll try to resolve this problem later but for the moment it will be just fine by removing offline gateway, thank you for your fast reply ! Have a nice day !

**Comment by jeandanyel** [comment] 2021-03-09 20:00
@Prometee I have the same issue when I change PayPal _(the official Sylius plugin)_ to Stripe.

**Comment by Prometee** [comment] 2021-03-10 12:19
@YellowFish085, @oneshoot41 and @jeandanyel I think I came to a reasonable fix, I have to test it with my closed sources wich handle subscription but it should be ok. Then I will release a new version of `flux-se/payum-stripe` to close this issue.

**Comment by Prometee** [comment] 2021-03-10 12:20
You can test it with a `composer req flux-se/payum-stripe:dev-master`

**Comment by jeandanyel** [comment] 2021-03-10 14:04
@Prometee It works 🥳 !

**Comment by Prometee** [comment] 2021-03-10 14:33
And it is working perfectly also for me, I pushed a new release, you can make the update :

```shell
composer up flux-se/payum-stripe
```

**Closed by Prometee** 2021-03-10 14:33 UTC
Labels: bug
